apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-cpbq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-cpbq
    app.kubernetes.io/part-of: my-app
  name: devfile-sample-cpbq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-cpbq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-cpbq
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/sbudhwar-1-tenant/my-app/devfile-sample-cpbq@sha256:fc384d4d93efa52c1588397dc67c94503d57095913c62a50616fb1d7ec0a773d
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
