apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-cpbq
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/sbudhwar-1-tenant/my-app/devfile-sample-cpbq@sha256:fc384d4d93efa52c1588397dc67c94503d57095913c62a50616fb1d7ec0a773d
        name: my-nodejs
        resources: {}
status: {}
